server:
  port: 8989

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/react_spring_blog
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        hibernate:
        "[format_sql]": true            #SQL 보기 좋게 출력
        "[user_sql_comments]": true     #SQL 생성시 주석 포함
        "[highlight_sql]": true         #SQL 색깔
        "[hbm2ddl.auto]": update
    open-in-view: true
    show-sql: true

  #default 1MB
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  header: "Authorization"
  prefix: "Bearer "
  secret: eyJhbGciOiJIUzUxMiJ9eyJzdWIiOiJ1c2VyIn0I2qOfhAZMGSH1pCecUH5sV2Lg2pSWNQMPzXsMcne6NJ1SlkBoirhGAmKfTYNcRyhu6nQtRzgAd6VXyttoX9A
  tokenExpirationTime: 18000

project:
  folderPath: "files/"